/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philipm.cs5.software.development.user.system;

import javax.swing.JOptionPane;
import philipm.cs5.software.development.server.system.UserInfo;

/**
 * Creates a form that allows a user to create an online game against a friend.
 * @author mortimer
 */
public class CreateGameAgainstFriend extends javax.swing.JFrame {
    private SessionInfo session;
    /**
     * Creates new form CreateGameAgainstFriend
     */
    private CreateGameAgainstFriend() {
        initComponents();
    }
    /**
     * Creates new form CreateGameAgainstFriend
     * @param session The session information of the user
     */
    public CreateGameAgainstFriend(SessionInfo session){
        this.session=session;//stores session
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        friendUserNameTxt = new javax.swing.JTextField();
        useCodeOrUsernameBtn = new javax.swing.JButton();
        fiveMinutesBtn = new javax.swing.JToggleButton();
        tenMinutesBtn = new javax.swing.JToggleButton();
        unlimitedBtn = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        createGameBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Game Against Friend");

        jLabel1.setText("Create Online Game Against Friend");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Friend Username");

        useCodeOrUsernameBtn.setText("Create Code to Share Instead");
        useCodeOrUsernameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useCodeOrUsernameBtnActionPerformed(evt);
            }
        });

        fiveMinutesBtn.setText("Five Minutes");
        fiveMinutesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveMinutesBtnActionPerformed(evt);
            }
        });

        tenMinutesBtn.setText("Ten Minutes");
        tenMinutesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenMinutesBtnActionPerformed(evt);
            }
        });

        unlimitedBtn.setText("Unlimited");
        unlimitedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlimitedBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Time Control");

        createGameBtn.setText("Create Game");
        createGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15)
                                .addComponent(fiveMinutesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenMinutesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unlimitedBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(backBtn))
                                .addGap(48, 48, 48)
                                .addComponent(friendUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(useCodeOrUsernameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(createGameBtn)
                        .addGap(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(friendUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(useCodeOrUsernameBtn)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiveMinutesBtn)
                    .addComponent(tenMinutesBtn)
                    .addComponent(unlimitedBtn)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(createGameBtn)
                .addGap(32, 32, 32)
                .addComponent(backBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       //takes user back to online menu
       OnlineMenu online = new OnlineMenu(session);
       online.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void fiveMinutesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveMinutesBtnActionPerformed
        // ensures that only one time control can be choosen
        if(fiveMinutesBtn.isSelected()){
            tenMinutesBtn.setSelected(false);
            unlimitedBtn.setSelected(false);
        }
    }//GEN-LAST:event_fiveMinutesBtnActionPerformed

    private void tenMinutesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenMinutesBtnActionPerformed
        // ensures that only one time control can be choosen
        if(tenMinutesBtn.isSelected()){
            fiveMinutesBtn.setSelected(false);
            unlimitedBtn.setSelected(false);
        }
    }//GEN-LAST:event_tenMinutesBtnActionPerformed

    private void unlimitedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlimitedBtnActionPerformed
        // ensures that only one time control can be choosen
        if(unlimitedBtn.isSelected()){
            fiveMinutesBtn.setSelected(false);
            tenMinutesBtn.setSelected(false);
        }
    }//GEN-LAST:event_unlimitedBtnActionPerformed

    private void useCodeOrUsernameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useCodeOrUsernameBtnActionPerformed
        //updates the username box and button text if relevant
        if(useCodeOrUsernameBtn.getText().equals("Create Code to Share Instead")){
            friendUserNameTxt.setEditable(false);
            friendUserNameTxt.setEnabled(false);
            useCodeOrUsernameBtn.setText("Input Username Instead");
        }else{
            friendUserNameTxt.setEnabled(true);
            friendUserNameTxt.setEditable(true);
            useCodeOrUsernameBtn.setText("Create Code to Share Instead");
        }
    }//GEN-LAST:event_useCodeOrUsernameBtnActionPerformed

    private void createGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGameBtnActionPerformed
        //creates a new game after performing relevant validation
        //gets time control to use
        int timeLeft=-100;
        if(fiveMinutesBtn.isSelected()){
            timeLeft=5*60;
        }else if(tenMinutesBtn.isSelected()){
            timeLeft=600;
        }else if(unlimitedBtn.isSelected()==false){
            JOptionPane.showMessageDialog(this,"Please select a time control.","Error",JOptionPane.OK_OPTION);
            return;
        }
        String userName="";//stores the username of the opponent
        if(useCodeOrUsernameBtn.getText().equals("Create Code to Share Instead")){
            userName=friendUserNameTxt.getText();
            if(!Validation.isPresent(userName) || userName.equals(session.getUsername())|| userName.equals(UserInfo.GUEST_ID)){//ensures that the username can't be empty or be that of the current user
                JOptionPane.showMessageDialog(this,"Please input a valid username.","Error",JOptionPane.OK_OPTION);
                return;
            }
            try{
                if(ThreadClient.isUserNameAlreadyTaken(userName)==false){//checks to see if username is taken
                    JOptionPane.showMessageDialog(this,"User not found. Please enter  a valid username.","Error",JOptionPane.OK_OPTION);
                    return;
                }
                if(ThreadClient.getOnlineGameData(userName)[2][0].equals("")==false){//checks to see if friend is already playing three games
                    JOptionPane.showMessageDialog(this,"User selected is currently playing three games. Users can not play more than three games.","Error",JOptionPane.OK_OPTION);
                    return;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "There has been an error when communicating with the server.","Error",JOptionPane.OK_OPTION);
                return;
            }
        }
        try{
            String code=ThreadClient.createGameAgainstFriend(session.getUsername(), userName, timeLeft);//creates the game
            if(code.equals("-1")){
                JOptionPane.showMessageDialog(this, "There has been an error when communicating with the server.","Error",JOptionPane.OK_OPTION);
            }else if(userName.equals("")){
                JOptionPane.showMessageDialog(this,"Game created. Game code "+code,"Game Created",JOptionPane.OK_OPTION);
            }else{
                JOptionPane.showMessageDialog(this,"Game created.","Game Created",JOptionPane.OK_OPTION);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "There has been an error when communicating with the server.","Error",JOptionPane.OK_OPTION);           
        }
        //takes user back to online menu
        OnlineMenu online = new OnlineMenu(session);
        online.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_createGameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGameAgainstFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGameAgainstFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGameAgainstFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGameAgainstFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateGameAgainstFriend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createGameBtn;
    private javax.swing.JToggleButton fiveMinutesBtn;
    private javax.swing.JTextField friendUserNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton tenMinutesBtn;
    private javax.swing.JToggleButton unlimitedBtn;
    private javax.swing.JButton useCodeOrUsernameBtn;
    // End of variables declaration//GEN-END:variables
}
