/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philipm.cs5.software.development.user.system;

import java.io.IOException;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import philipm.cs5.software.development.server.system.Fixture;

/**
 * Form that allows the leader to edit and view fixtures/results.
 * @author mortimer
 */
public class FixturesAndResultsLeader extends javax.swing.JFrame  {
    private SessionInfo session;//stores the session information
    private static final String[]COLUMN_NAMES=new String[]{"White","Black","Result"};//stores the name of the columns used in the table
    private String[][][]fixturesAndResults;//stores the fixtures and results
    private int roundIndex;//stores which round is currently being viewed
    private boolean haveFixturesBeenGenerated;//stores whether the fixtures have been generated yet
    //constants used to indicate the game result to the leader
    private static final String WHITE_WIN="White Win";private static final String BLACK_WIN="Black Win";
    private static final String GAME_DRAWN="Draw";private static final String GAME_NOT_YET_PLAYED="Game Not Yet Played";
    private static final String BYE_GAME="Bye Game";
    private static final String[]GAME_STATE_OPTIONS=new String[]{GAME_DRAWN,WHITE_WIN,BLACK_WIN,GAME_NOT_YET_PLAYED,BYE_GAME};//stores the options used by the JComboBox editor which allows the leader to alter the game state
    /**
     * Creates new form FixturesAndResults
     */
    private FixturesAndResultsLeader() {
        initComponents();
    }
    /**
     * Creates new form FixturesAndResults
     * @param session The session information
     * @throws Exception An exception may occur when attempting to retrieve the fixtures and results from the server
     */
    public FixturesAndResultsLeader(SessionInfo session) throws Exception{
        initComponents();
        this.session=session;
        //sets various table characteristics for a better user experience
        fixturesAndResultsTbl.getTableHeader().setReorderingAllowed(false);
        fixturesAndResultsTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fixturesAndResultsTbl.setDefaultEditor(Object.class, null);
        updateVariablesServer();//updates fixtures and results by getting the data from the server
        updateTable();//updates the table based on the fixtures and results
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fixturesAndResultsTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        roundLbl = new javax.swing.JLabel();
        prevRoundBtn = new javax.swing.JButton();
        nextRoundBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        startNewSeasonBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fixtures and Results");

        fixturesAndResultsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "White", "Black", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fixturesAndResultsTbl);
        if (fixturesAndResultsTbl.getColumnModel().getColumnCount() > 0) {
            fixturesAndResultsTbl.getColumnModel().getColumn(0).setResizable(false);
            fixturesAndResultsTbl.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("Fixtures and Results");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        roundLbl.setText("Round 1");

        prevRoundBtn.setText("Previous Round");
        prevRoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevRoundBtnActionPerformed(evt);
            }
        });

        nextRoundBtn.setText("Next Round");
        nextRoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRoundBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save Results");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        startNewSeasonBtn.setText("Start New Season");
        startNewSeasonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewSeasonBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(backBtn)
                        .addGap(235, 235, 235)
                        .addComponent(prevRoundBtn)
                        .addGap(69, 69, 69)
                        .addComponent(nextRoundBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBtn)
                        .addGap(46, 46, 46)
                        .addComponent(startNewSeasonBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(roundLbl)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(roundLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backBtn)
                        .addComponent(prevRoundBtn)
                        .addComponent(nextRoundBtn)
                        .addComponent(startNewSeasonBtn))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //takes user back to the form that they came from
        if(session.getIsClubLeader()){//takes leader back to leader form
            int confirm = JOptionPane.showConfirmDialog(this, "Would you like to go back? Any unsaved changes (if there are any) will be lost.", "Back?", JOptionPane.YES_NO_CANCEL_OPTION);
            if(confirm!=JOptionPane.YES_OPTION){
                return;
            }
            WestCrossChessClubLeader leader = new WestCrossChessClubLeader(session);
            leader.setVisible(true);
            this.dispose();return;
        }else{
            WestCrossChessClubMember member = new WestCrossChessClubMember(session);
            member.setVisible(true);
            this.dispose();return;            
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void nextRoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRoundBtnActionPerformed
        //stores any changes made to the fixtures / results and takes the leader to the next round
        updateFixturesArray();
        roundIndex++;
        updateTable();
    }//GEN-LAST:event_nextRoundBtnActionPerformed

    private void prevRoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevRoundBtnActionPerformed
        //stores any changes made to the fixtures / results and takes the leader to the previous round
        updateFixturesArray();
        roundIndex--;
        updateTable();
    }//GEN-LAST:event_prevRoundBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        //saves the changes (if any) and sends the updated fixtures/results to the server
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you would like to save the fixtures/results? This means that any changes you have made will be saved.", "Save?", JOptionPane.YES_NO_CANCEL_OPTION);
        if(confirm!=JOptionPane.YES_OPTION){
            return;
        }
        // saves the fixtures in their current form to the server
        updateFixturesArray();
        try{
            ThreadClient.updateFixturesAndResults(fixturesAndResults);
        }catch(IOException e){
            JOptionPane.showMessageDialog(this,"An error occurred when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            Menu menu = new Menu(session);menu.setVisible(true);this.dispose();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void startNewSeasonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewSeasonBtnActionPerformed
        //seeks user confirmation and then starts a new season
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you would like to start a new season? Doing so will mean that all previous data (including fixtures, results and the league table) will be lost.", "New Season?", JOptionPane.YES_NO_CANCEL_OPTION);
        if(confirm!=JOptionPane.YES_OPTION){
            return;
        }
        try{
            ThreadClient.createNewSeason();//creates the new season
            updateVariablesServer();//updates the variables and table based on the new data
            updateTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"An error occurred when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            Menu menu = new Menu(session);menu.setVisible(true);this.dispose();
        }
        
    }//GEN-LAST:event_startNewSeasonBtnActionPerformed
    /**
     * Updates the fixtures array game results based on the JTable. This only updates the local array.
     */
    private void updateFixturesArray(){
        //loops through all results in the current round and updates the fixture/results array.
        //this essentially results in any changes to the game states being saved to the array.
        String result;
        for(int match=0;match<fixturesAndResults[roundIndex][0].length;match++){
            result=fixturesAndResultsTbl.getValueAt(match, 2).toString();
            //converts result to computer representation of game state
            switch (result) {
                case BLACK_WIN:
                    fixturesAndResults[roundIndex][2][match]=Fixture.GAME_BLACK_WIN;
                    break;
                case WHITE_WIN:
                    fixturesAndResults[roundIndex][2][match]=Fixture.GAME_WHITE_WIN;
                    break;
                case GAME_DRAWN:
                    fixturesAndResults[roundIndex][2][match]=Fixture.GAME_DRAW;
                    break;
                case GAME_NOT_YET_PLAYED:
                    fixturesAndResults[roundIndex][2][match]=Fixture.GAME_NOT_YET_PLAYED;
                    break;
                default:
                    //if game is a bye
                    fixturesAndResults[roundIndex][2][match]=Fixture.BYE_GAME_STATE;
                    break;
            }
        }
    }
    /**
     * Requests data from the server and updates variables accordingly
     * @throws Exception An exception may occur when attempting to retrieve information from the server
     */
    private void updateVariablesServer() throws Exception{
        fixturesAndResults= ThreadClient.getFixturesAndResults();//gets fixtures/results from the server
        haveFixturesBeenGenerated=fixturesAndResults.length!=0;//determines whether the fixtuers have actually been generated. A fixtures array of length 0 indicates that the fxitures have not been generated.
        roundIndex=0;//sets the round index to 0
    }
    /**
     * Updates the table based on the data stored in the object
     */
    private void updateTable(){
        if(haveFixturesBeenGenerated){
            //displays the fixtyres/results of the current round in the table
            roundLbl.setText("Round "+String.valueOf(roundIndex+1));//displays which round number is being viewed
            //enables/disables the previous and next round buttons based on whether the previous/next round exists
            prevRoundBtn.setVisible(true);
            prevRoundBtn.setEnabled(roundIndex!=0);
            nextRoundBtn.setEnabled(roundIndex!=(fixturesAndResults.length-1));
            nextRoundBtn.setVisible(true);
            //displays the table
            jScrollPane1.setEnabled(true);jScrollPane1.setVisible(true);
            fixturesAndResultsTbl.setEnabled(true);fixturesAndResultsTbl.setVisible(true);
            //uses the fixtures and results array to generate the table data
            String[][]tableData=new String[fixturesAndResults[0][0].length][COLUMN_NAMES.length];
            //in the form: white, black, result
            for(int player=0;player<tableData.length;player++){
                tableData[player][0]=fixturesAndResults[roundIndex][0][player];
                if(tableData[player][0].equals(Fixture.BY_NAME)){//bye player names are replaced with an empty string
                    tableData[player][0]="";
                }
                tableData[player][1]=fixturesAndResults[roundIndex][1][player];
                if(tableData[player][1].equals(Fixture.BY_NAME)){
                    tableData[player][1]="";
                }
                //converts the game state from a computer form to a form that is understandable by humans
                switch (fixturesAndResults[roundIndex][2][player]) {
                    case Fixture.BYE_GAME_STATE:
                        tableData[player][2]=BYE_GAME;
                        break;
                    case Fixture.GAME_DRAW:
                        tableData[player][2]=GAME_DRAWN;
                        break;
                    case Fixture.GAME_WHITE_WIN:
                        tableData[player][2]=WHITE_WIN;
                        break;
                    case Fixture.GAME_BLACK_WIN:
                        tableData[player][2]=BLACK_WIN;
                        break;
                    default:
                        //game has not yet been played
                        tableData[player][2]=GAME_NOT_YET_PLAYED;
                        break;
                }
            }
            JComboBox <String>game = new JComboBox<String>(GAME_STATE_OPTIONS);//creates a new ComboBox that allows the game results to be edited by the leader
            DefaultTableModel model = new DefaultTableModel(tableData, COLUMN_NAMES){//creates a new table model using the data generated
                /**
                 * Determines whether the cell is editable. Only game results can be edited. Only game results that contain two human players can be edited.
                 * @param row The row number of the cell
                 * @param column The column number of the cell
                 * @return Whether the cell is editable
                 */
                @Override
                public boolean isCellEditable(int row, int column){
                    //a game result can only be altered if the game is against two human players
                    return !(column==2 && (tableData[row][1].equals("") || tableData[row][0].equals("")));
                }
            };
            fixturesAndResultsTbl.setModel(model);//sets the table to the generated model
            fixturesAndResultsTbl.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(game));//sets it so that the game results are edited using a JComboBox. This avoids the need to validate inputs as only valid game states can be selected.
            return;
        }else{
            //updates the form to display to the user that the fixtures have not yet been generated
            roundLbl.setText("The fixtures have not yet been generated");
            saveBtn.setVisible(false);saveBtn.setEnabled(false);
            prevRoundBtn.setEnabled(false);prevRoundBtn.setVisible(false);
            nextRoundBtn.setEnabled(false);nextRoundBtn.setVisible(false);
            fixturesAndResultsTbl.setEnabled(false);fixturesAndResultsTbl.setVisible(false);
            jScrollPane1.setEnabled(false);jScrollPane1.setVisible(false);
            return;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixturesAndResultsLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixturesAndResultsLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixturesAndResultsLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixturesAndResultsLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixturesAndResultsLeader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable fixturesAndResultsTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextRoundBtn;
    private javax.swing.JButton prevRoundBtn;
    private javax.swing.JLabel roundLbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton startNewSeasonBtn;
    // End of variables declaration//GEN-END:variables
}
