/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philipm.cs5.software.development.user.system;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import philipm.cs5.software.development.server.system.UserInfo;

/**
 * Creates a form that allows the user to log in with their log in credentials
 * @author mortimer
 */
public class LogIn extends javax.swing.JFrame {
    private boolean showPassword=false;//stores whether the password should be masked or not
    private final char DEFAULT_ECHO_CHAR;//stores tge default character used to mask the password
    private static final String TERMS_AND_CONS_FILE="haveTermsAndConditionsBeenAccepted.txt";//stores the text file location that stores whether the terms and conditions have been agreed to
    /**
     * Creates new form LogIn
     */
    public LogIn() {   
        initComponents();
        try{
            //checks to see if terms and conditions have already been agreed to
            FileReader read = new FileReader(TERMS_AND_CONS_FILE);
            BufferedReader buffReader = new BufferedReader(read);
            boolean termsAccepted=buffReader.readLine().equals("true");
            buffReader.close();read.close();
            if(!termsAccepted){
                //displays the terms and conditions of using the software
                JOptionPane.showMessageDialog(this, "This program makes use of the Stockfish 12 chess engine. This program is licensed to use Stockfish 12 under the GNU General Public License Version 3 (GPLv3)."
                +System.lineSeparator()+"A copy of this license can be found in the directory for this program titled 'GNU.txt'. The source code to Stockfish 12 may be found at: "
                +System.lineSeparator()+"https://github.com/official-stockfish/Stockfish or https://stockfishchess.org/download/ or https://stockfishchess.org/"
                        +System.lineSeparator()+"Additionally, the source code can be found in the program directory in a zip file titled 'Stockfish-sf_12.zip'"
                +System.lineSeparator()+"This message will not be displayed again. Please do NOT alter any text files in the program repository."+
                        System.lineSeparator()+"For any further assistance, please contact philipmortimer99@aol.com","Message"
                        +System.lineSeparator()+"Furthermore, when creating an account, all data (apart from your password) can be viewed and altered by"
                        +System.lineSeparator()+"the leader of the West Cross Chess Club. By using this software, you consent that you are ok with this."
                        ,JOptionPane.OK_OPTION);
            }
            //sets it so that this message is not displayed again
            FileWriter write= new FileWriter(TERMS_AND_CONS_FILE);
            BufferedWriter buffWrite = new BufferedWriter(write);
            buffWrite.write("true");
            buffWrite.flush();write.flush();buffWrite.close();write.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this,"An unexpected error occurred: "+e,"Error",JOptionPane.OK_OPTION);
        } 
        DEFAULT_ECHO_CHAR=passwordTxt.getEchoChar();
        this.getRootPane().setDefaultButton(logInBtn);//sets the log in button as the default button
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameOrEmailAddressTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        showOrHidePasswordBtn = new javax.swing.JButton();
        changeInternetSettingsBtn = new javax.swing.JButton();
        logInBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        guestLogInBtn = new javax.swing.JButton();
        createAccountBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");

        jLabel1.setText("Username / Email Address");

        jLabel2.setText("Password");

        showOrHidePasswordBtn.setText("Show Password");
        showOrHidePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOrHidePasswordBtnActionPerformed(evt);
            }
        });

        changeInternetSettingsBtn.setText("Change Online Settings");
        changeInternetSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeInternetSettingsBtnActionPerformed(evt);
            }
        });

        logInBtn.setText("Log In");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        guestLogInBtn.setText("Log In As Guest");
        guestLogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestLogInBtnActionPerformed(evt);
            }
        });

        createAccountBtn.setText("Create Account");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameOrEmailAddressTxt)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(exitBtn)
                        .addGap(31, 31, 31)
                        .addComponent(changeInternetSettingsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(createAccountBtn)
                        .addGap(18, 18, 18)
                        .addComponent(guestLogInBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showOrHidePasswordBtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logInBtn)
                        .addGap(18, 18, 18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameOrEmailAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showOrHidePasswordBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeInternetSettingsBtn)
                    .addComponent(logInBtn)
                    .addComponent(exitBtn)
                    .addComponent(guestLogInBtn)
                    .addComponent(createAccountBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Ensures the password field is masked or not depending on the option selected.
 * @param evt The button being pressed
 */
    private void showOrHidePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOrHidePasswordBtnActionPerformed
        //hides or makes the password visible
        showPassword=!showPassword;
        if(showPassword){
            //makes the password visible as plain text
            showOrHidePasswordBtn.setText("Hide Password");
            char c=0;
            passwordTxt.setEchoChar(c);
        }else{
            //masks the password
            showOrHidePasswordBtn.setText("Show Password");
            passwordTxt.setEchoChar(DEFAULT_ECHO_CHAR);
        }
    }//GEN-LAST:event_showOrHidePasswordBtnActionPerformed
    /**
     * Exits the system after asking for user confirmation.
     * @param evt The exit button being pressed by the user
     */
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you would like to exit?", "Exit?", JOptionPane.YES_NO_CANCEL_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed
    /**
     * Takes the user to a form that allows them to edit their online settings.
     * @param evt The user pressing the appropriate button
     */
    private void changeInternetSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeInternetSettingsBtnActionPerformed
        ChangeInternetSettings change = new ChangeInternetSettings();
        change.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changeInternetSettingsBtnActionPerformed

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        //logs user in via server
        //validates input somewhat before querying server
        if(usernameOrEmailAddressTxt.getText().equals(UserInfo.GUEST_ID)|| usernameOrEmailAddressTxt.getText().equals(UserInfo.GUEST_ID_EMAIL)){//banned inputs reserved for guest ids
            JOptionPane.showMessageDialog(this,"You can't log in with this ID.","Error",JOptionPane.OK_OPTION);
            return;
        }
        if(usernameOrEmailAddressTxt.getText().contains("@")){//for email address log in
            try {
                //checks to see if email address exists
                if(ThreadClient.isEmailAddressAlreadyTaken(usernameOrEmailAddressTxt.getText())==false){
                    JOptionPane.showMessageDialog(this, "The email address was not found.","Error",JOptionPane.OK_OPTION);
                    return;                     
                }
                //attempts to log user in
                UserInfo user = ThreadClient.logInWithEmailAddress(usernameOrEmailAddressTxt.getText(), new String(passwordTxt.getPassword()));
                if(user.getIsPasswordCorrect()==false){//if password does not match email
                    JOptionPane.showMessageDialog(this, "The password is incorrect.","Error",JOptionPane.OK_OPTION);
                    return;
                }
                //takes user to menu if log in was succesful
                Menu menu = new Menu(new SessionInfo(user.getUserName(), user.getIsClubMember(), user.getIsClubLeader()));menu.setVisible(true);this.dispose();return;//takes user to menu with appropriate session information
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "A network error has occured. This may be due to your network settings or the server. "+ex,"Error",JOptionPane.OK_OPTION);   
                return;
            }
        }else{//for username
            try{
                //attempts to log user in with username
                UserInfo user = ThreadClient.logInWithUserName(usernameOrEmailAddressTxt.getText(), new String(passwordTxt.getPassword()));//gets user info from server
                if(user.getUserFound()==false){//displays appropraite message if the username was not found
                    JOptionPane.showMessageDialog(this, "The username was not found.","Error",JOptionPane.OK_OPTION);
                    return;
                }
                if(user.getIsPasswordCorrect()==false){//displays appropraite message if the password entered was wrong
                    JOptionPane.showMessageDialog(this, "The password is incorrect.","Error",JOptionPane.OK_OPTION);
                    return;
                }
                Menu menu = new Menu(new SessionInfo(user.getUserName(), user.getIsClubMember(), user.getIsClubLeader()));menu.setVisible(true);this.dispose();return;//takes user to menu with appropriate session information
                //takes user to menu having created session info object to store relevant data
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "A network error has occured. This may be due to your network settings or the server. "+e,"Error",JOptionPane.OK_OPTION);   
                return;
            }
        }
    }//GEN-LAST:event_logInBtnActionPerformed

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        //takes user to form which allows them to create an account
        CreateAccount account = new CreateAccount();//loads the create account form
        account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void guestLogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestLogInBtnActionPerformed
        Menu menu = new Menu(SessionInfo.createGuestSession());menu.setVisible(true);this.dispose();
        //logs user in as guest and takes them to main menu
    }//GEN-LAST:event_guestLogInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeInternetSettingsBtn;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton guestLogInBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logInBtn;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton showOrHidePasswordBtn;
    private javax.swing.JTextField usernameOrEmailAddressTxt;
    // End of variables declaration//GEN-END:variables
}
