/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philipm.cs5.software.development.user.system;

import javax.swing.JOptionPane;

/**
 * Creates a menu form that allows a user to access various parts of the system
 * @author mortimer
 */
public class Menu extends javax.swing.JFrame {
    SessionInfo session;//the session information of the current user
    /**
     * Creates new form Menu
     */
    private Menu() {
        initComponents();
    }
    /**
     * Creates new form Menu
     * @param sess The session information of the current user
     */
    public Menu(SessionInfo sess){//overloading is used to store session info and run the form
        session =sess;
        initComponents();
        //sets the username label depending on the session information
        if(sess.getIsGuest()){
            logInInfoLbl.setText("You are currently logged in as a Guest.");
            onlineBtn.setEnabled(false);
        }else{
            logInInfoLbl.setText("Username: "+sess.getUsername());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chessClubBtn = new javax.swing.JButton();
        onlineBtn = new javax.swing.JButton();
        offlineBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        logInInfoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jLabel1.setText("West Cross Chess Club");
        jLabel1.setToolTipText("");

        chessClubBtn.setText("West Cross Chess Club");
        chessClubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chessClubBtnActionPerformed(evt);
            }
        });

        onlineBtn.setText("Online");
        onlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineBtnActionPerformed(evt);
            }
        });

        offlineBtn.setText("Offline");
        offlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offlineBtnActionPerformed(evt);
            }
        });

        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        logInInfoLbl.setText("Username:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(293, 293, 293))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(logOutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chessClubBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onlineBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(offlineBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logInInfoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(logInInfoLbl)
                .addGap(26, 26, 26)
                .addComponent(chessClubBtn)
                .addGap(51, 51, 51)
                .addComponent(onlineBtn)
                .addGap(56, 56, 56)
                .addComponent(offlineBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutBtn)
                    .addComponent(Exit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        //exits sytem upon user confirmation
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you would like to exit?", "Exit?", JOptionPane.YES_NO_CANCEL_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // logs user out after confirmation
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you would like to log out?", "Log out?", JOptionPane.YES_NO_CANCEL_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            LogIn log = new LogIn();
            log.setVisible(true);
            this.dispose();
        }        
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void offlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offlineBtnActionPerformed
        // takes user to form for offline games
        OfflinePlay offline = new OfflinePlay(session);
        offline.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_offlineBtnActionPerformed

    private void onlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineBtnActionPerformed
        //takes user to online game form
        OnlineMenu online = new OnlineMenu(session);
        online.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_onlineBtnActionPerformed

    private void chessClubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chessClubBtnActionPerformed
        // takes the user to the west cross chess club menu. This form differs depending on what type of user is attempting to access the form
        if(session.getIsGuest()){//takes the user to the chess club form for guests
            WestCrossChessClubGuest chessClubGuest = new WestCrossChessClubGuest(session);
            chessClubGuest.setVisible(true);
            this.dispose();
        }else if(session.getIsClubMember()==false){//takes the user to the chess club form for non-member users
            WestCrossChessClubUser chessClubUser = new WestCrossChessClubUser(session);
            chessClubUser.setVisible(true);
            this.dispose();            
        }else if(session.getIsClubMember() && session.getIsClubLeader()==false){//takes the user to the chess club form for member users
            WestCrossChessClubMember chessClubMember = new WestCrossChessClubMember(session);
            chessClubMember.setVisible(true);
            this.dispose();             
        }else{//takes the user to the chess club form for the chess club leader
            WestCrossChessClubLeader chessClubLeader = new WestCrossChessClubLeader(session);
            chessClubLeader.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_chessClubBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton chessClubBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logInInfoLbl;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton offlineBtn;
    private javax.swing.JButton onlineBtn;
    // End of variables declaration//GEN-END:variables
}
