/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philipm.cs5.software.development.user.system;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Creates a new form that allows club members to access features of the chess club available to them.
 * @author mortimer
 */
public class WestCrossChessClubMember extends javax.swing.JFrame {
    private boolean error=false;//stores whether an error has occurred
    private boolean isFormInitialised=false;//stores whether the form has been intialised
    private SessionInfo session;//stores the session data
    /**
     * Creates new form WestCrossChessClubMember
     */
    private WestCrossChessClubMember() {
        initComponents();
    }
    /**
     * Creates new form WestCrossChessClubMember
     * @param session The session information of the current member
     */
    public WestCrossChessClubMember(SessionInfo session){
        this.session=session;//stores the session data
        initComponents();//initialises the form components
        leaveClubBtn.setBackground(Color.red);//sets the button the appropriate colour
        attemptToLoadContactInfo();//attempts to laod the contact details onto the form
        isFormInitialised=true;//flags that the form has now been intialised
    }
    /**
     * Loads contact details onto the appropriate forms
     */
    private void attemptToLoadContactInfo(){
        try{
            String[]contactInfo=ThreadClient.getChessClubContactDetails();//loads contact information from the server
            phoneNumberTxt.setText(contactInfo[0]);emailTxt.setText(contactInfo[1]);//sets the contact information on the relevant fields
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"An error occurred when attempting to get the club contact information from the server. Error: "+e,"Error",JOptionPane.OK_OPTION);
            error=true;//flags the fact that an error has occurred
            if(isFormInitialised){
                Menu menu = new Menu(session);
                menu.setVisible(true);this.dispose();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phoneNumberTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        leaveClubBtn = new javax.swing.JButton();
        viewFixturesAndResultsBtn = new javax.swing.JButton();
        viewLeagueTableBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("West Cross Chess Club");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("West Cross Chess Club");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Contact Details");

        jLabel15.setText("Phone Number");

        phoneNumberTxt.setEditable(false);

        jLabel16.setText("Email Address");

        emailTxt.setEditable(false);

        jLabel17.setText("You are a member of the West Cross Chess Club.");

        leaveClubBtn.setText("Leave the West Cross Chess Club");
        leaveClubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveClubBtnActionPerformed(evt);
            }
        });

        viewFixturesAndResultsBtn.setText("View Fixtures and Results");
        viewFixturesAndResultsBtn.setMaximumSize(new java.awt.Dimension(165, 29));
        viewFixturesAndResultsBtn.setMinimumSize(new java.awt.Dimension(165, 29));
        viewFixturesAndResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFixturesAndResultsBtnActionPerformed(evt);
            }
        });

        viewLeagueTableBtn.setText("View League Table");
        viewLeagueTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLeagueTableBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(emailTxt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(viewFixturesAndResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewLeagueTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaveClubBtn))
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(viewFixturesAndResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(leaveClubBtn)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(viewLeagueTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //takes the user back to the menu
        Menu menu = new Menu(session);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //checks to see if an error has occured during the form intialisation. If it has, the user is taken back to the menu.
        if(error){
            Menu menu = new Menu(session);
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void leaveClubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveClubBtnActionPerformed
        // lets the user leave the chess club after confirming they wish to do so
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you would like to leave the chess club?", "Quit?", JOptionPane.YES_NO_CANCEL_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            //removes user from the chess club
            try{
                ThreadClient.removeUserFromChessClub(session.getUsername());
                session.setIsClubMember(false);
                Menu menu = new Menu(session);menu.setVisible(true);this.dispose();
                return;
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error when communicating with the server. "+e,"Error",JOptionPane.OK_OPTION);
                Menu menu = new Menu(session);menu.setVisible(true);this.dispose();
                return;
            }
        }else{
            return;
        }   
    }//GEN-LAST:event_leaveClubBtnActionPerformed

    private void viewLeagueTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLeagueTableBtnActionPerformed
        //takes the user to a form to view the current league table
        try{
            String[][]leagueTable=ThreadClient.getLeagueTable();//requests the league table from the server
            if(leagueTable.length==0){
                //if the no fixtures have been generated, then the league table requires all the chess club members as an input instead
                String[]allPlayers=ThreadClient.getMembersOfChessClub();
                LeagueTable tab = new LeagueTable(session, allPlayers);
                tab.setVisible(true);this.dispose();return;
            }
            LeagueTable tab = new LeagueTable(session, leagueTable);
            tab.setVisible(true);this.dispose();return;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            return;
        }
    }//GEN-LAST:event_viewLeagueTableBtnActionPerformed

    private void viewFixturesAndResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFixturesAndResultsBtnActionPerformed
        //takes member to form where they can view the fixtures and results
        try{
            FixturesAndResults fixtures = new FixturesAndResults(session);
            fixtures.setVisible(true);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_viewFixturesAndResultsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WestCrossChessClubMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leaveClubBtn;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JButton viewFixturesAndResultsBtn;
    private javax.swing.JButton viewLeagueTableBtn;
    // End of variables declaration//GEN-END:variables
}
