/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philipm.cs5.software.development.user.system;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Creates a new form that allows the leader of the chess club to access features of the chess club available to the leader.
 * @author mortimer
 */
public class WestCrossChessClubLeader extends javax.swing.JFrame {
    private boolean error=false;//stores whether an error occurred when loading the form
    private boolean isFormInitialised=false;//stores whether the form has been intialised
    private SessionInfo session;//stores the session data
    private boolean areContactDetailsBeingEdited=false;//stores whether the contact detais are currently being altered
    private String phoneNumber;private String email;//stores the default club contact details
    /**
     * Creates new form WestCrossChessClubLeader
     */
    private WestCrossChessClubLeader() {
        initComponents();
    }
    /**
     * Creates new form WestCrossChessClubLeader
     * @param session The session information of the user
     */
    public WestCrossChessClubLeader(SessionInfo session){
        this.session=session;
        initComponents();
        cancelChangesBtn.setVisible(false);cancelChangesBtn.setEnabled(false);
        createNewLeaderBtn.setBackground(Color.red);//sets the button the appropriate colour
        attemptToLoadContactInfo();//attempts to laod the contact information to the form
        isFormInitialised=true;//stores that the form has been initialised
    }
    /**
     *Loads contact details onto the appropriate forms
     */
    private void attemptToLoadContactInfo(){
        try{
            String[]contactInfo=ThreadClient.getChessClubContactDetails();//gets contact details
            phoneNumberTxt.setText(contactInfo[0]);emailTxt.setText(contactInfo[1]);//loads contact details onto form 
            phoneNumber=contactInfo[0];email=contactInfo[1];//stores contact details
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"An error occurred when attempting to get the club contact information from the server. Error: "+e,"Error",JOptionPane.OK_OPTION);
            error=true;//shows that an error has occurred and goes to the menu if appropriate
            if(isFormInitialised){
                Menu menu = new Menu(session);
                menu.setVisible(true);this.dispose();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phoneNumberTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        createNewLeaderBtn = new javax.swing.JButton();
        fixturesAndResultsBtn = new javax.swing.JButton();
        viewLeagueTableBtn = new javax.swing.JButton();
        changeContactDetailsBtn = new javax.swing.JButton();
        cancelChangesBtn = new javax.swing.JButton();
        handelRequestsBtn = new javax.swing.JButton();
        viewMemberDetailsBtn = new javax.swing.JButton();
        nonMemberBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("West Cross Chess Club");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("West Cross Chess Club");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Contact Details");

        jLabel15.setText("Phone Number");

        phoneNumberTxt.setEditable(false);

        jLabel16.setText("Email Address");

        emailTxt.setEditable(false);

        jLabel17.setText("You are the leader of the West Cross Chess Club");

        createNewLeaderBtn.setText("Appoint New West Cross Chess Club Leader");
        createNewLeaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewLeaderBtnActionPerformed(evt);
            }
        });

        fixturesAndResultsBtn.setText("Fixtures and Results");
        fixturesAndResultsBtn.setMaximumSize(new java.awt.Dimension(165, 29));
        fixturesAndResultsBtn.setMinimumSize(new java.awt.Dimension(165, 29));
        fixturesAndResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixturesAndResultsBtnActionPerformed(evt);
            }
        });

        viewLeagueTableBtn.setText("View League Table");
        viewLeagueTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLeagueTableBtnActionPerformed(evt);
            }
        });

        changeContactDetailsBtn.setText("Change Contact Details");
        changeContactDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeContactDetailsBtnActionPerformed(evt);
            }
        });

        cancelChangesBtn.setText("Cancel Changes");
        cancelChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelChangesBtnActionPerformed(evt);
            }
        });

        handelRequestsBtn.setText("Requests to Join The Club");
        handelRequestsBtn.setMaximumSize(new java.awt.Dimension(165, 29));
        handelRequestsBtn.setMinimumSize(new java.awt.Dimension(165, 29));
        handelRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handelRequestsBtnActionPerformed(evt);
            }
        });

        viewMemberDetailsBtn.setText("Member Details");
        viewMemberDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMemberDetailsBtnActionPerformed(evt);
            }
        });

        nonMemberBtn.setText("Non - Members");
        nonMemberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonMemberBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fixturesAndResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewLeagueTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(handelRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewMemberDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createNewLeaderBtn)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(emailTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelChangesBtn)
                        .addGap(54, 54, 54)
                        .addComponent(changeContactDetailsBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel14)))
                .addGap(106, 106, 106)
                .addComponent(nonMemberBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeContactDetailsBtn)
                            .addComponent(cancelChangesBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nonMemberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixturesAndResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLeagueTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(handelRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewMemberDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(createNewLeaderBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //takes the user back to the menu
        Menu menu = new Menu(session);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //checks to see if any error occurred when initialising the form. If it has, the current form is disposed and the user is taken back to the menu
        if(error){
            Menu menu = new Menu(session);
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void createNewLeaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewLeaderBtnActionPerformed
        // appoints a new chess club leader
        //asks for comfirmation before making the appointment
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to make somebody else the leader? This will mean that you will no longer be the leader.", "Proceed?", JOptionPane.YES_NO_CANCEL_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            //appoints somebody else as the chess club leader
            String newLeader = JOptionPane.showInputDialog(this,"Please input the username of the new leader:");
            if(newLeader==null){//if the user pressses cancel on the input dialog boc, nothing should occur
                return;
            }
            try{
                //performs validation
                if(ThreadClient.isUserNameAlreadyTaken(newLeader)==false){//checks to see that the username chosen is actually valid
                    JOptionPane.showMessageDialog(this,"This user does not exist. Please input a real user.","Error",JOptionPane.OK_OPTION);
                    return;
                }
                if(newLeader.equals(session.getUsername())){//if the new leader is just the same as the current leader, nothing needs to occur
                    return;
                }
                ThreadClient.setUserAsClubLeader(newLeader);//sets the new leader
                session.setIsClubLeader(false);//updates the session data
                JOptionPane.showMessageDialog(this,"You are no longer the club leader.","Success",JOptionPane.OK_OPTION);
                Menu menu = new Menu(session);menu.setVisible(true);this.dispose();//takes the user back to the menu
                return;
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error when communicating with the server. "+e,"Error",JOptionPane.OK_OPTION);
                Menu menu = new Menu(session);menu.setVisible(true);this.dispose();
                return;
            }
        }else{
            return;
        }   
    }//GEN-LAST:event_createNewLeaderBtnActionPerformed

    private void viewLeagueTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLeagueTableBtnActionPerformed
        //takes the leader to a form that allows them to veiw the current club league table
        try{
            String[][]leagueTable=ThreadClient.getLeagueTable();//requests the league table from the server
            if(leagueTable.length==0){
                //if the fixtures have not been generated yet, a list of all club members is requested from the server. The leader is then taken to the form
                String[]allPlayers=ThreadClient.getMembersOfChessClub();
                LeagueTable tab = new LeagueTable(session, allPlayers);
                tab.setVisible(true);this.dispose();return;
            }
            LeagueTable tab = new LeagueTable(session, leagueTable);
            tab.setVisible(true);this.dispose();return;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            Menu menu = new Menu(session);menu.setVisible(true);this.dispose();
            return;
        }
    }//GEN-LAST:event_viewLeagueTableBtnActionPerformed

    private void fixturesAndResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixturesAndResultsBtnActionPerformed
        //takes the leader to a form that allows the, to view and edit the fixtures and results
        try{
            FixturesAndResultsLeader fixtures = new FixturesAndResultsLeader(session);
            fixtures.setVisible(true);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            Menu menu = new Menu(session);menu.setVisible(true);this.dispose();
        }
    }//GEN-LAST:event_fixturesAndResultsBtnActionPerformed

    private void changeContactDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeContactDetailsBtnActionPerformed
        //attempts to change the contact details or save changes to contact details
        if(areContactDetailsBeingEdited){
            //attempts to save changes to server
            //updates form to reflect the fact that the contact details are no longer activel being edited
            areContactDetailsBeingEdited=false;
            cancelChangesBtn.setVisible(false);cancelChangesBtn.setEnabled(false);
            changeContactDetailsBtn.setText("Change Contact Details");
            phoneNumberTxt.setEditable(false);
            emailTxt.setEditable(false);
            try{
                ThreadClient.setChessClubContactDetails(phoneNumberTxt.getText(), emailTxt.getText());//saves changes
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
                Menu menu = new Menu(session);menu.setVisible(true);this.dispose();return;
            }
            phoneNumber=phoneNumberTxt.getText();email=emailTxt.getText();
        }else{//sets it so that the leader can edit the contact details
            //updates the form to allow the contact details to be changed
            cancelChangesBtn.setVisible(true);cancelChangesBtn.setEnabled(true);
            changeContactDetailsBtn.setText("Save Changes");
            areContactDetailsBeingEdited=true;
            phoneNumber=phoneNumberTxt.getText();email=emailTxt.getText();
            phoneNumberTxt.setEditable(true);
            emailTxt.setEditable(true);
        }
    }//GEN-LAST:event_changeContactDetailsBtnActionPerformed

    private void cancelChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelChangesBtnActionPerformed
        // cancels changes made and exits editing mode
        areContactDetailsBeingEdited=false;
        cancelChangesBtn.setVisible(false);cancelChangesBtn.setEnabled(false);
        changeContactDetailsBtn.setText("Change Contact Details");
        phoneNumberTxt.setEditable(false);
        emailTxt.setEditable(false);
        emailTxt.setText(email);phoneNumberTxt.setText(phoneNumber);//reverts contact details to their values before editing began
    }//GEN-LAST:event_cancelChangesBtnActionPerformed

    private void handelRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handelRequestsBtnActionPerformed
        // takes the leader to a form that handles requests to join the club
        try{
            RequestsToJoinClub request = new RequestsToJoinClub(session);
            request.setVisible(true);
            this.dispose();return;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            Menu menu = new Menu(session);menu.setVisible(true);this.dispose();return;
        }
    }//GEN-LAST:event_handelRequestsBtnActionPerformed

    private void viewMemberDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMemberDetailsBtnActionPerformed
        // takes the leader to a form where they may view and edit certain user details of club members. They may also add and remove
        //users from the club in this form
        try{
            MemberDetails mem = new MemberDetails(session);mem.setVisible(true);this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            Menu menu = new Menu(session);menu.setVisible(true);this.dispose();return;
        }
    }//GEN-LAST:event_viewMemberDetailsBtnActionPerformed

    private void nonMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonMemberBtnActionPerformed
        // takes the user to a form where they may edit user info. This form allows non-members to be added to the club.
        //it also allows for accounts to be deleted
        try{
            NonMemberDetails non = new NonMemberDetails(session);non.setVisible(true);this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error when communicating with the server: "+e,"Error",JOptionPane.OK_OPTION);
            Menu menu = new Menu(session);menu.setVisible(true);this.dispose();return;            
        }
    }//GEN-LAST:event_nonMemberBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WestCrossChessClubLeader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelChangesBtn;
    private javax.swing.JButton changeContactDetailsBtn;
    private javax.swing.JButton createNewLeaderBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton fixturesAndResultsBtn;
    private javax.swing.JButton handelRequestsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nonMemberBtn;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JButton viewLeagueTableBtn;
    private javax.swing.JButton viewMemberDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
