/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philipm.cs5.software.development.user.system;

import javax.swing.JOptionPane;

/**
 * Creates a new form that allows non-member users to access features of the chess club available to them.
 * @author mortimer
 */
public class WestCrossChessClubUser extends javax.swing.JFrame {
    private boolean error=false;//stores whether an error has occurred
    private boolean isFormInitialised=false;//stores whether the form has been initialised
    private SessionInfo session;//stores the session data
    /**
     * Creates new form WestCrossChessClubUser
     */
    private WestCrossChessClubUser() {
        initComponents();
    }
    /**
     * Creates new form WestCrossChessClubUser
     * @param session The session information of the user
     */
    public WestCrossChessClubUser(SessionInfo session){
        this.session=session;
        initComponents();
        attemptToLoadContactInfo();//attempts to load
        if(error==false){//if no error has occured, the form attempts to load whether the user has requested to join the club
            setFormBasedOnWhetherUserHasRequestedToJoinTheClub();
        }
        isFormInitialised=true;//indicates that the form has now been intialised
    }
    /**
     * Updates the form based on whether the user has requested to join the club
     */
    private void setFormBasedOnWhetherUserHasRequestedToJoinTheClub(){
        try{
            boolean hasRequested = ThreadClient.getHasUserRequestedToJoinChessClub(session.getUsername());//gets whether the user has requested to join the club
            //updates the button and label text based on whether the user has requested to join the club
            if(hasRequested){
                requestToJoinClubBtn.setText("Withdraw request to join the West Cross Chess Club");
                infoLbl.setText("Please feel free to contact the club or withdraw your request to join.");
            }else{
                requestToJoinClubBtn.setText("Request to Join the West Cross Chess Club");
                infoLbl.setText("Please feel free to contact the club or request to join.");
            }
        }catch(Exception e){
            error=true;//flags that an error has occurred
            JOptionPane.showMessageDialog(this,"An error occurred when communicating with the server. Error: "+e,"Error",JOptionPane.OK_OPTION);
            if(isFormInitialised){
                Menu menu = new Menu(session);menu.setVisible(true);
                this.dispose();
            }
        }
    }
    /**
     * Loads contact details onto the appropriate forms
     */
    private void attemptToLoadContactInfo(){
        try{
            String[]contactInfo=ThreadClient.getChessClubContactDetails();//gets the contact details from the server
            phoneNumberTxt.setText(contactInfo[0]);emailTxt.setText(contactInfo[1]);//laods the details to the form
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"An error occurred when attempting to get the club contact information from the server. Error: "+e,"Error",JOptionPane.OK_OPTION);
            error=true;
            if(isFormInitialised){
                Menu menu = new Menu(session);
                menu.setVisible(true);this.dispose();
                
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phoneNumberTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        infoLbl = new javax.swing.JLabel();
        requestToJoinClubBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("West Cross Chess Club");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("West Cross Chess Club");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Contact Details");

        jLabel15.setText("Phone Number");

        phoneNumberTxt.setEditable(false);

        jLabel16.setText("Email Address");

        emailTxt.setEditable(false);

        jLabel17.setText("You are not a member of the West Cross Chess Club.");

        infoLbl.setText("Please feel free to contact the club or request to join.");

        requestToJoinClubBtn.setText("Request to Join the West Cross Chess Club");
        requestToJoinClubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestToJoinClubBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(emailTxt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(backBtn)))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requestToJoinClubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoLbl)
                            .addComponent(jLabel17))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLbl)
                        .addGap(18, 18, 18)
                        .addComponent(requestToJoinClubBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //takes the user back to the menu
        Menu menu = new Menu(session);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //checks to see if an error has occurred during form intialisation. If it has, then form is disposed and the user is taken back to the menu
        if(error){
            Menu menu = new Menu(session);
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void requestToJoinClubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestToJoinClubBtnActionPerformed
        // adds a request to join the West Cross Chess Club or withdraws it depending on the requests statis
        try{
            ThreadClient.changeRequestToJoinClubStatus(session.getUsername());//chanegs request status
        }catch(Exception e){
           JOptionPane.showMessageDialog(this,"An error occurred when attempting to communicate with the server. Error: "+e,"Error",JOptionPane.OK_OPTION);
            error=true;
            if(isFormInitialised){
                Menu menu = new Menu(session);
                menu.setVisible(true);this.dispose();
            }
            return;
        }
        setFormBasedOnWhetherUserHasRequestedToJoinTheClub();//updates form based on request status
    }//GEN-LAST:event_requestToJoinClubBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WestCrossChessClubUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WestCrossChessClubUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JButton requestToJoinClubBtn;
    // End of variables declaration//GEN-END:variables
}
